version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    image: striker-backend
    depends_on:
      - mongo
    environment:
      PORT: "8080"
      MONGODB_URI: "mongodb://mongo/test"
    ports:
      - "8080:8080"
  frontend:
    image: striker-frontend
    depends_on:
      - backend
    environment:
      PORT: "8081"
      BACKEND_URI: "http://backend:8080"
    ports:
      - "8081:8081"
