name: Striker CI
on: pull_request
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install Gradle Dependencies
        run: ./gradlew assemble
      - name: Run Tests
        run: ./gradlew check
