name: Deploy on Production
on:
  push:
    branches:
      - master
jobs:
  deploy-on-heroku:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      # TODO can we get rid of this step or replace it with if statement?
      - name: not-deleted-filter
        uses: actions/bin/filter@master
        with:
          args: not deleted
      - name: Build
        uses: MrRamych/gradle-actions/openjdk-12@2.1
        with:
          args: jib -Djib.to.auth.username=_ -Djib.to.auth.password=${HEROKU_API_KEY}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        uses: actions/heroku@master
        with:
          args: container:release web --app=${HEROKU_APP}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: striker-vn
      - name: Health Check
        uses: actions/bin/curl@master
        with:
          args: https://${HEROKU_APP}.herokuapp.com/actuator/health | grep UP
        env:
          HEROKU_APP: striker-vn
      - name: Version Check
        uses: actions/bin/curl@master
        with:
          args: https://${HEROKU_APP}.herokuapp.com/actuator/info | grep ${BUILD_COMMIT}
        env:
          BUILD_COMMIT: ${{ github.sha }}
          HEROKU_APP: striker-vn
      - name: Verify
        uses: MrRamych/gradle-actions/openjdk-12@2.1
        with:
          args: test -DserverUrl=https://${HEROKU_APP}.herokuapp.com -Dusername=${TEST_USERNAME} -Dpassword=${TEST_PASSWORD}
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          HEROKU_APP: striker-vn
