name: Deploy on Production
on:
  push:
    branches:
      - master
jobs:
  deploy-on-heroku:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew jib -Djib.to.auth.username=_ -Djib.to.auth.password=${HEROKU_API_KEY}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        uses: actions/heroku@1.0.0
        with:
          args: container:release web --app=${HEROKU_APP}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: striker-vn
      - name: Health Check
        run: curl https://${HEROKU_APP}.herokuapp.com/actuator/health | grep UP
        env:
          HEROKU_APP: striker-vn
      - name: Version Check
        run: curl https://${HEROKU_APP}.herokuapp.com/actuator/info | grep ${BUILD_COMMIT}
        env:
          BUILD_COMMIT: ${{ github.sha }}
          HEROKU_APP: striker-vn
      - name: Verify
        run: ./gradlew test -DserverUrl=https://${HEROKU_APP}.herokuapp.com -Dusername=${TEST_USERNAME} -Dpassword=${TEST_PASSWORD}
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          HEROKU_APP: striker-vn
